server:
  port: 8080
---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/bb-item?autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop